### ISSUE TITLE
update commands

### ISSUE THREAD

**Issue by ArshadSheik** [thegeekyb0y/linuxcommands#4]
nano - opens up an editor to edit the files
date - used to display or set system date and time
reboot - instructs the system to restart or reboot
shutdown - used for shutting down the system
rcp - used to copy files from one computer to another computer

**Comment by thegeekyb0y** [comment]
bro , make a PR and edit the file, I will merge it automatically. Thanks for the issue

**Comment by ArshadSheik** [comment]
sure
